config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :users
    root to: "items#index"
    resources :items do
      resources :orders, only:[:index, :create]
    end

  namespace :admins do
    root to: 'toppages#index'
    resources :items, only: [:new, :create]
  end
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :admin
  belongs_to :user
  belongs_to :category
   belongs_to :shipping_days
   has_one :purchase_history
   has_one_attached :image

 with_options presence: true do
   validates :image
   validates :name
   validates :description
   validates :category_id
   validates :shipping_days_id
   validates :price, numericality: { greater_than_or_equal_to: 300, less_than_or_equal_to: 9_999_999 }
 end

  validates :category_id, :shipping_days_id, numericality: { other_than: 1 }

end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < Admins::ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
     if @item.save
          flash[:success] = "itemが正常に作成されました"
          redirect_to root_path
     else
          flash.now[:danger] = "itemが正常に作成されませんでした"
          render :new
     end
  end

    private
    
    def item_params
      params.require(:item).permit(:name, :price, :description, :category_id, :shipping_days_id, :image).merge(admin_id: current_admin.id)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :ensure_current_user, only: [:edit, :update]
  
  def index
    @items = Item.all.order(created_at: "DESC")
  end

  def show
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to action: :show
    else
      render :edit
    end
  end

  def destroy
    if @pitem.user_id == current_user.id
     @item.destroy
    end
    redirect_to root_path
  end

    private
    def item_params
      params.require(:product).permit(:name, :price, :description, :category_id, :shipping_days_id, :image).merge(user_id: current_user.id)
    end

    def set_item
      @item = Item.find(params[:id])
    end

    def ensure_current_user
      if @item.user_id != current_user.id || @item.purchase_history.presence
        redirect_to action: :index
      end
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('tkms-logo-color.png' , size: '185x50'), "/" %>

  </header>
  <div class="items-sell-main">
   <h2 class="items-sell-title">商品の情報を入力</h2>
   <%= form_with model: @product, local: true do |f| %>
      <%= render 'shared/error_messages', model: f.object %>
      <%# 出品画像 %>
      <div class="img-upload">
        <div class="weight-bold-text">
          掲載画像
          <span class="indispensable">必須</span>
        </div>
        <div class="click-upload">
          <p>
            クリックしてファイルをアップロード
          </p>
          <%= f.file_field :image, id:"item-image" %>
        </div>
      </div>
      <%# /出品画像 %>
      <%# 商品名と商品説明 %>
      <div class="new-items">
        <div class="weight-bold-text">
          商品名
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
        <div class="items-explain">
          <div class="weight-bold-text">
            商品の説明
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_area :description, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）" ,rows:"7" ,maxlength:"1000" %>
        </div>
      </div>
      <%# /商品名と商品説明 %>
  
      <%# 商品の詳細 %>
      <div class="items-detail">
        <div class="weight-bold-text">商品の詳細</div>
        <div class="form">
          <div class="weight-bold-text">
            カテゴリー
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        </div>
      </div>
      <%# /商品の詳細 %>
  
      <%# 配送について %>
      <div class="items-detail">
        <div class="weight-bold-text question-text">
          <span>配送について</span>
          <a class="question" href="#">?</a>
        </div>
        <div class="form">
          <div class="weight-bold-text">
            発送までの日数
            <span class="indispensable">必須</span>
          </div>
          <%= f.collection_select(:shipping_days_id, ShippingDays.all, :id, :name, {}, {class:"select-box", id:"item-scheduled-delivery"}) %>
        </div>
      </div>
      <%# /配送について %>
  
      <%# 販売価格 %>
      <div class="sell-price">
        <div class="weight-bold-text question-text">
          <span>販売価格<br>(¥300〜9,999,999)</span>
          <a class="question" href="#">?</a>
        </div>
        <div>
          <div class="price-content">
            <div class="price-text">
              <span>価格</span>
              <span class="indispensable">必須</span>
            </div>
            <span class="sell-yen">¥</span>
            <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
          </div>
          <div class="price-content">
            <span>販売手数料 (10%)</span>
            <span>
              <span id='add-tax-price'></span>円
            </span>
          </div>
          <div class="price-content">
            <span>販売利益</span>
            <span>
              <span id='profit'></span>円
          </div>
          </span>
        </div>
      </div>
      <%# /販売価格 %>
  
      <%# 注意書き %>
      <%# /注意書き %>
      <%# 下部ボタン %>
      <div class="sell-btn-contents">
        <%= f.submit "掲載する", class:"sell-btn" %>
        <%=link_to 'もどる', root_path, class:"back-btn" %>
      </div>
      <%# /下部ボタン %>
      </div>
   <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#">プライバシーポリシー</a></li>
      <li><a href="#">フリマ利用規約</a></li>
      <li><a href="#">特定商取引に関する表記</a></li>
    </ul>
    <%= link_to image_tag('tkms-logo-color.png' , size: '185x50'), "/" %>
    <p class="inc">
      ©︎Furima,Inc.
    </p>
  </footer>
</div>

app/views/items/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <%# 画面上部の「人生を変えるフリマアプリ」帯部分 %>
      <div class='store-btn'>
      <%= link_to image_tag("tiktok-logo.png", class:"tiktok-btn"), "#" %>
      <%= link_to image_tag("instagram-logo.png", class:"instagram-btn"), "#" %>
      <%= link_to image_tag("twitter-logo.png", class:"twitter-btn"), "#" %>
    </div>
  <%# /画面上部の「人生を変えるフリマアプリ」帯部分  %>

  <%# FURIMAが選ばれる3つの理由部分 %>
  <div class='title-contents'>
    <h2 class='service-title'>
    TKMS BASE
    </h2>
    <p class='service-explain'>
    大槌町浪板海岸
    </p>
    <p class='service-explain'>
    これが自慢の地元の海です。
    </p>
  </div>

  <div class='select-reason-contents'>
    <h2 class='title'>
      XXXXXXXXXXXXXXXXX
    </h2>
    <ul class='reason-lists'>
      <li class='list'>
        <%= image_tag "sample.png", class:"list-pict" %>
        <span class='reason-list-number'>1</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>みんなで</span>
          明るく
        </h3>
        <p class='reason-list-description'>
          XXXXXXXXXXXXXXXXX
        </p>
      </li>
      <li class='list'>
        <%= image_tag "sample.png", class:"list-pict" %>
        <span class='reason-list-number'>2</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>みんなで</span>
          楽しく
        </h3>
        <p class='reason-list-description'>
          XXXXXXXXXXXXXXXXX
        </p>
      </li>
      <li class='list'>
        <%= image_tag "sample.png", class:"list-pict" %>
        <span class='reason-list-number'>3</span>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>みんなで</span>
          おもしろく
        </h3>
        <p class='reason-list-description'>
          XXXXXXXXXXXXXXXXX
        </p>
      </li>
    </ul>
  </div>
  <%# /TKMS BASEが選ばれる3つの理由部分 %>

  <div class='ad-contents'>
    <h2 class='ad-title'>
    </h2>
    <p class='ad-explain'>
    </p>
    <p class='ad-explain'>
    </p>
  </div>

  <div class='feature-contents'>
    <h2 class='title'>
      TKMS BASEの特徴
    </h2>
    <ul class='feature-lists'>
      <li class='list'>
        <%= image_tag "furima-intro04.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          XXXXXXXXXXXXXXXXX
        </h3>
        <p class='feature-list-description'>
          XXXXXXXXXXXXXXXXX
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro05.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          XXXXXXXXXXXXXXXXXX
        </h3>
        <p class='feature-list-description'>
          XXXXXXXXXXXXXXXXX
        </p>
      </li>
      <li class='list'>
        <%= image_tag "furima-intro06.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          XXXXXXXXXXXXXXXXX
        </h3>
        <p class='feature-list-description'>
        XXXXXXXXXXXXXXXXX
        </p>
      </li>
    </ul>
  </div>

  <div class='item-contents'>
    <h2 class='title'>ピックアップカテゴリー</h2>
    <div class="subtitle" >
         新商品
    </div>
      <ul class='item-lists'>
       <% if @items.exists? %>
       <% @items.each do |item| %>
         <li class='list'>
          <%= link_to item_path(item.id) do %>
          <div class='item-img-content'>
            <%= image_tag item.image, class: "item-img"%>
            <% if item.purchase_history != nil %>
              <div class='sold-out'>
                <span>Sold Out!!</span>
              </div>
            <% end %>

          </div>
          <div class='item-info'>
            <h3 class='item-name'>
              <%= item.name %>
            </h3>
            <div class='item-price'>
              <span><%= item.price %>円<br><%= item.shipping_days.name %></span>
              <div class='star-btn'>
                <%= image_tag "star.png", class:"star-icon" %>
                <span class='star-count'>0</span>
              </div>
            </div>
          </div>
          <% end %>
       </li>
      <% end %>
      
      <% else %>
        <li class='list'>
          <%= link_to '#' do %>
            <div class='item-info'>
              <h3 class='item-name'>
                商品を出品してね！
              </h3>
              <div class='item-price'>
                <span>99999999円<br>(税込み)</span>
                <div class='star-btn'>
                  <%= image_tag "star.png", class:"star-icon" %>
                  <span class='star-count'>0</span>
                </div>
              </div>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<%= link_to( new_item_path, class: 'purchase-btn') do %>
  <%= image_tag 'icon.png' , size: '100x50' ,class: "purchase-btn-icon" %>
<% end %>
<%= render "shared/footer" %>

app/views/items/show.html.erb
<%= render "shared/header" %>

<%# 商品の概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @product.name %>
    </h2>
    <div class="item-img-content">
      <%= image_tag @product.image ,class:"item-box-img" %>

      <% if @product.purchase_history != nil %>
      <div class="sold-out">
        <span>Sold Out!!</span>
      </div>
      <% end %>

    </div>
    <div class="item-price-box">
      <span class="item-price">
        ¥<%= @product.price%>
      </span>
      <span class="item-postage">
        <%= @product.shipping_days.name %>
      </span>
    </div>

    <% if user_signed_in? && @product.purchase_history == nil %>
      <%if current_user.id == @product.user_id %>
          <%= link_to "商品の編集", edit_product_path(@product.id), method: :get, class: "item-red-btn" %>
          <p class="or-text">or</p>
          <%= link_to "削除", product_path(@product.id), method: :delete, class:"item-destroy" %>
        <% else %>
          <%= link_to "購入画面に進む", product_orders_path(@product.id), class:"item-red-btn"%>
        <% end %>
    <% end %>

    <div class="item-explain-box">
      <span><%= @product.description %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">カテゴリー</th>
          <td class="detail-value"><%= @product.category.name %></td>
        </tr>
        <tr>
          <th class="detail-item">発送日の目安</th>
          <td class="detail-value"><%= @product.shipping_days.name %></td>
        </tr>
      </tbody>
    </table>
    <div class="option">
      <div class="favorite-btn">
        <%= image_tag "star.png" ,class:"favorite-star-icon" ,width:"20",height:"20"%>
        <span>お気に入り 0</span>
      </div>
      <div class="report-btn">
        <%= image_tag "flag.png" ,class:"report-flag-icon" ,width:"20",height:"20"%>
        <span>不適切な商品の通報</span>
      </div>
    </div>
  </div>
  <%# /商品の概要 %>

  <div class="comment-box">
    <form>
      <textarea class="comment-text"></textarea>
      <p class="comment-warn">
        相手のことを考え丁寧なコメントを心がけましょう。
        <br>
        不快な言葉遣いなどは利用制限や退会処分となることがあります。
      </p>
      <button type="submit" class="comment-btn">
        <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
        <span>コメントする<span>
      </button>
    </form>
  </div>
  <div class="links">
    <a href="#" class="change-item-btn">
      ＜ 前の商品
    </a>
    <a href="#" class="change-item-btn">
      後ろの商品 ＞
    </a>
  </div>
  <a href="#" class="another-item"><%= @product.category.name %>をもっと見る</a>
</div>

<%= render "shared/footer" %>